services:

  server:
    container_name: avtonet_telegram_server
    restart: "unless-stopped"
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.server
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
    volumes:
      - server-data:/app

volumes:
  server-data: